First branch
tag1consulting/ansible-role-letsencrypt pull request #1
Opened 2019-06-28 00:00 UTC by kindlehl

When reviewing, you should ignore all the yaml files under `./files`. They are configuration files for boulder, they work because boulder works.

2019-07-03 19:45 UTC, kindlehl commented on tasks/acme-test.yaml
> +  become: true
It was easier to shell this out than to use the `docker_service` module on Centos 7 because ansible just **HAS** to run everything through python, and installing docker{,-compose} is easier with `geerlingguy.docker`, though it uses the package manager to install, not pip. This shouldn't really matter in the long run since this task file should only be ran in a testing environment IMO.

2019-07-03 19:48 UTC, kindlehl commented on tasks/generate.yml
> +    -out /etc/letsencrypt/live/{{ vhost['servername'] }}/cert.pem
Sadly, I had to manually run openssl commands here because Centos7 uses a decade-old version of pyOpenSSL, which does not work with ansibles openssl modules.

2019-07-11 23:50 UTC, kindlehl commented
Once/if this gets merged, the requirements.yml in ansible-systems (branches tag1internal and travelsentry) need to update the ref to master.

2019-07-12 00:00 UTC, kindlehl commented on files/docker-compose.yml.boulder
> +version: '3'
You can 100% ignore the contents of this file. I just grabbed a copy and modified some parameters to make it work nicely

2019-07-12 00:00 UTC, kindlehl commented on files/rate-limit-policies.yml
> +# See cmd/shell.go for definitions of these rate limits.
You can ignore this file also. Its just a hand-modified copy.

2019-07-12 00:01 UTC, kindlehl commented on files/va.json
> +{
Ignore this file too

2019-07-12 00:02 UTC, kindlehl commented on tasks/acme-test.yaml
> +  become: true
Also, docker_service is changed to docker_compose (or vice versa) and whatever I write here is removed in the jump from ansible 2.7 to 2.8

2019-07-12 03:05 UTC, jeffsheltren requested changes
Overall looks good to me. I made some minor comments. I didn't review the LE setup logic closely but @gchaix can hopefully take a closer look at that.

2019-07-12 03:05 UTC, jeffsheltren commented on tasks/Debian.yml
> +  become: true
Might be just me but I find this much more readable if the module name (`shell` in this case) is the first line after `name`.

2019-07-12 03:05 UTC, jeffsheltren commented on tasks/init.yaml
> +    virtualenv: /root/.certbot_env
Please make this path a variable and add it `defaults/main.yaml`. And then you can use it in the `cutover.sh` script as well.

2019-07-12 03:05 UTC, jeffsheltren commented on tasks/acme-test.yaml
> +  shell: chcon -Rt container_file_t /root/boulder
Is there a reason this needs to be in `/root`? Could it go in a configurable tmp dir instead?

2019-07-12 03:05 UTC, jeffsheltren commented on tasks/main.yml
>    become: true
I believe this should be:

```
vars:
  ansible_become: true
```
So that it gets passed in correctly.

2019-07-12 17:01 UTC, kindlehl commented on tasks/acme-test.yaml
> +  shell: chcon -Rt container_file_t /root/boulder
I put it in root since I didn't think this would be useful to run in production. It might actually be nice in a staging environment or something. I'll toss in a variable

2019-07-12 17:17 UTC, kindlehl commented on tasks/main.yml
>    become: true
Either method works. `acme-test.yaml` does all sorts of stuff like installing packages and copying files into `/root` and communicating with the docker daemon. It does all that stuff fine. If its a matter of style, I can change it. I personally prefer just using become because its shorter.

2019-07-12 17:42 UTC, kindlehl commented on tasks/Debian.yml
> +  become: true
Agreed. I found and corrected many other instances of this type of lint

2019-07-12 19:48 UTC, kindlehl commented on tasks/init.yaml
> +    virtualenv: /root/.certbot_env
done

2019-09-09 17:38 UTC, nnewton commented on tasks/generate.yml
> +    -out /etc/letsencrypt/live/{{ vhost['servername'] }}/cert.pem
tell me about it

2019-09-09 17:39 UTC, merged